### ISSUE TITLE
does not build

### ISSUE THREAD

**Issue by ronenmagid** [kevoj/electron-react-ant-boilerplate#7]
cannot build using` yarn install... `

```
0 warnings and 6 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/ronenmagid/dev/electron-react-ant-boilerplate/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command \"/usr/local/Cellar/node/12.4.0/bin/node\" \"/Users/ronenmagid/dev/electron-react-ant-boilerplate/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/ronenmagid/dev/electron-react-ant-boilerplate/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/ronenmagid/dev/electron-react-ant-boilerplate/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64\" \"--napi_version=4\" \"--node_abi_napi=napi\" \"--napi_build_version=0\" \"--node_napi_label=node-v72\"
gyp ERR! cwd /Users/ronenmagid/dev/electron-react-ant-boilerplate/node_modules/fsevents
gyp ERR! node -v v12.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/12.4.0/bin/node /Users/ronenmagid/dev/electron-react-ant-boilerplate/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/ronenmagid/dev/electron-react-ant-boilerplate/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/ronenmagid/dev/electron-react-ant-boilerplate/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/ronenmagid/dev/electron-react-ant-boilerplate/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 18.6.0
node-pre-gyp ERR! command \"/usr/local/Cellar/node/12.4.0/bin/node\" \"/Users/ronenmagid/dev/electron-react-ant-boilerplate/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/ronenmagid/dev/electron-react-ant-boilerplate/node_modules/fsevents
node-pre-gyp ERR! node -v v12.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/12.4.0/bin/node /Users/ronenmagid/dev/electron-react-ant-boilerplate/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/ronenmagid/dev/[1/4] ⠁ node-sass
```

**Comment by bytesleo** [comment]
Try an LTS of Nodejs version, I recommend version 10
